# Yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches:
      - development
      - master

  pull_request:
    types:
      - opened
      - synchronize

env:
  NODE_VERSION: 22

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - run: pnpm exec eslint .

      - run: pnpm exec tsc --noEmit

      - run: pnpm exec vitest run
